#import <Preferences/PSListController.h>
#import "HBAppearanceSettings.h"
#import <CepheiPrefs/HBRootListController.h>
#import <Cephei/HBRespringController.h>
#import <Cephei/HBPreferences.h>
#import <spawn.h>
#define TABLE_BG colorWithRed:0.94901961 green:0.94901961 blue:0.96862745 alpha:1

#define OUTLINE colorWithRed:0.9 green:0.9 blue:0.90764706 alpha:1


/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:24:06 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class UIImageView, NSString, PSSpecifier, PSTableCellHighlightContext, NSURLSession, NSURL, UILongPressGestureRecognizer;

@interface PSTableCell : UITableViewCell {

	id _value;
	UIImageView* _checkedImageView;
	BOOL _checked;
	BOOL _shouldHideTitle;
	NSString* _hiddenTitle;
	int _alignment;
	SEL _pAction;
	id _pTarget;
	BOOL _cellEnabled;
	PSSpecifier* _specifier;
	long long _type;
	BOOL _lazyIcon;
	BOOL _lazyIconDontUnload;
	BOOL _lazyIconForceSynchronous;
	NSString* _lazyIconAppID;
	BOOL _reusedCell;
	PSTableCellHighlightContext* _customHighlightContext;
	NSURLSession* _urlSession;
	NSURL* _lazyIconURL;
	BOOL _forceHideDisclosureIndicator;
	BOOL _isCopyable;
	UILongPressGestureRecognizer* _longTapRecognizer;
}

@property (assign,nonatomic) BOOL isCopyable;                                               //@synthesize isCopyable=_isCopyable - In the implementation block
@property (nonatomic,retain) UILongPressGestureRecognizer * longTapRecognizer;              //@synthesize longTapRecognizer=_longTapRecognizer - In the implementation block
@property (assign,nonatomic) long long type;                                                //@synthesize type=_type - In the implementation block
@property (nonatomic,retain) PSSpecifier * specifier;                                       //@synthesize specifier=_specifier - In the implementation block
@property (assign,nonatomic) BOOL reusedCell;                                               //@synthesize reusedCell=_reusedCell - In the implementation block
@property (assign,nonatomic) BOOL forceHideDisclosureIndicator;                             //@synthesize forceHideDisclosureIndicator=_forceHideDisclosureIndicator - In the implementation block
+(id)reuseIdentifierForSpecifier:(id)arg1 ;
+(Class)cellClassForSpecifier:(id)arg1 ;
+(id)stringFromCellType:(long long)arg1 ;
+(id)reuseIdentifierForClassAndType:(long long)arg1 ;
+(id)reuseIdentifierForBasicCellTypes:(long long)arg1 ;
+(long long)cellTypeFromString:(id)arg1 ;
+(double)defaultCellHeight;
+(long long)cellStyle;
-(void)layoutSubviews;
-(void)setAlignment:(int)arg1 ;
-(void)dealloc;
-(void)setChecked:(BOOL)arg1 ;
-(void)setTitle:(id)arg1 ;
-(id)title;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(void)setType:(long long)arg1 ;
-(long long)type;
-(SEL)action;
-(id)titleLabel;
-(id)target;
-(void)setTarget:(id)arg1 ;
-(void)setValue:(id)arg1 ;
-(id)value;
-(BOOL)canBecomeFirstResponder;
-(id)scriptingInfoWithChildren;
-(void)setAction:(SEL)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(id)_contentString;
-(void)copy:(id)arg1 ;
-(void)setIcon:(id)arg1 ;
-(id)_disclosureChevronImage:(BOOL)arg1 ;
-(id)_checkmarkImage:(BOOL)arg1 ;
-(double)textFieldOffset;
-(id)iconImageView;
-(BOOL)isChecked;
-(id)valueLabel;
-(void)reloadWithSpecifier:(id)arg1 animated:(BOOL)arg2 ;
-(void)setReusedCell:(BOOL)arg1 ;
-(void)forceSynchronousIconLoadOnNextIconLoad;
-(void)cellRemovedFromView;
-(BOOL)canBeChecked;
-(void)highlightCellForDuration:(double)arg1 animateUnighlight:(BOOL)arg2 ;
-(void)_invalidateHighlightContext;
-(void)_updateAccessoryTypeForSpecifier:(id)arg1 ;
-(void)longPressed:(id)arg1 ;
-(void)setShouldHideTitle:(BOOL)arg1 ;
-(id)blankIcon;
-(id)getLazyIcon;
-(id)getLazyIconID;
-(id)lazyIconQueue:(id)arg1 ;
-(void)setCellEnabled:(BOOL)arg1 ;
-(void)setValueChangedTarget:(id)arg1 action:(SEL)arg2 specifier:(id)arg3 ;
-(void)setCellTarget:(id)arg1 ;
-(void)setCellAction:(SEL)arg1 ;
-(id)_urlSession;
-(id)cellTarget;
-(SEL)cellAction;
-(void)setForceHideDisclosureIndicator:(BOOL)arg1 ;
-(id)getIcon;
-(BOOL)cellEnabled;
-(BOOL)reusedCell;
-(BOOL)forceHideDisclosureIndicator;
-(BOOL)isCopyable;
-(void)setIsCopyable:(BOOL)arg1 ;
-(UILongPressGestureRecognizer *)longTapRecognizer;
-(void)setLongTapRecognizer:(UILongPressGestureRecognizer *)arg1 ;
-(id)_automationID;
-(void)setSpecifier:(PSSpecifier *)arg1 ;
-(PSSpecifier *)specifier;
-(id)_copyableText;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3 ;
-(void)refreshCellContentsWithSpecifier:(id)arg1 ;
-(BOOL)canReload;
-(id)titleTextLabel;

@end

@interface BOPRootListController : HBRootListController
@end



@interface LifeguardBigTextCell : PSTableCell{
	UILabel* _label;
}
	-(UIColor*) coverUp;
@end
